from datetime import datetime
from typing import Optional

from sqlalchemy import DateTime, ForeignKey, Integer, String
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.db.database import Base


class EmailVerificationToken(Base):
    """
    A single-use, time-limited token for verifying a user's email address.

    Security notes
    --------------
    - Only the *hash* of the token is stored here (token_hash).  The raw
      token is generated by the application, sent to the user by email, and
      never written to the database.
    - ``expires_at`` must be checked on every verification attempt.
    - ``used_at`` is set on first successful use; subsequent attempts with
      the same token must be rejected even if the token has not expired.
    """

    __tablename__ = "email_verification_tokens"

    id: Mapped[int] = mapped_column(
        Integer,
        primary_key=True,
        index=True,
    )

    user_id: Mapped[int] = mapped_column(
        ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )

    # SHA-256 (or similar) hash of the raw verification token.
    # Never store the raw token.
    token_hash: Mapped[str] = mapped_column(
        String(255),
        nullable=False,
        unique=True,
        index=True,
    )

    expires_at: Mapped[datetime] = mapped_column(
        DateTime,
        nullable=False,
    )

    # Set to the timestamp of first successful use; NULL means unused.
    used_at: Mapped[Optional[datetime]] = mapped_column(
        DateTime,
        nullable=True,
        default=None,
    )

    created_at: Mapped[datetime] = mapped_column(
        DateTime,
        default=datetime.utcnow,
        nullable=False,
    )

    # Relationship back to the owning User
    user = relationship(
        "User",
        back_populates="email_verification_tokens",
    )
